# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_data.proto',
  package='image_data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10image_data.proto\x12\nimage_data\")\n\x05Image\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\tImageData\x12!\n\x06images\x18\x01 \x03(\x0b\x32\x11.image_data.Image\"\x9c\x01\n\x08Response\x12\x35\n\timage_map\x18\x01 \x03(\x0b\x32\".image_data.Response.ImageMapEntry\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x1a\x46\n\rImageMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.image_data.ImageData:\x02\x38\x01\x62\x06proto3'
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='image_data.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='image_data.Image.image_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='image_data.Image.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=73,
)


_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='image_data.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='image_data.ImageData.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=121,
)


_RESPONSE_IMAGEMAPENTRY = _descriptor.Descriptor(
  name='ImageMapEntry',
  full_name='image_data.Response.ImageMapEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='image_data.Response.ImageMapEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='image_data.Response.ImageMapEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=280,
)

_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='image_data.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_map', full_name='image_data.Response.image_map', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='image_data.Response.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_RESPONSE_IMAGEMAPENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=280,
)

_IMAGEDATA.fields_by_name['images'].message_type = _IMAGE
_RESPONSE_IMAGEMAPENTRY.fields_by_name['value'].message_type = _IMAGEDATA
_RESPONSE_IMAGEMAPENTRY.containing_type = _RESPONSE
_RESPONSE.fields_by_name['image_map'].message_type = _RESPONSE_IMAGEMAPENTRY
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_data_pb2'
  # @@protoc_insertion_point(class_scope:image_data.Image)
  })
_sym_db.RegisterMessage(Image)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'image_data_pb2'
  # @@protoc_insertion_point(class_scope:image_data.ImageData)
  })
_sym_db.RegisterMessage(ImageData)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {

  'ImageMapEntry' : _reflection.GeneratedProtocolMessageType('ImageMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESPONSE_IMAGEMAPENTRY,
    '__module__' : 'image_data_pb2'
    # @@protoc_insertion_point(class_scope:image_data.Response.ImageMapEntry)
    })
  ,
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'image_data_pb2'
  # @@protoc_insertion_point(class_scope:image_data.Response)
  })
_sym_db.RegisterMessage(Response)
_sym_db.RegisterMessage(Response.ImageMapEntry)


_RESPONSE_IMAGEMAPENTRY._options = None
# @@protoc_insertion_point(module_scope)
